services:
  edsphc-source:
    image: mysql:8.0
    env_file:
      - ./source/edsphc-source.env
    container_name: "edsphc-source"
    restart: "no"
    ports:
      - 4406:3306
    volumes:
      - ./source/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
    networks:
      - overlay

  edsphc-replica:
    image: mysql:8.0
    env_file:
      - ./replica/edsphc-replica.env
    container_name: "edsphc-replica"
    restart: "no"
    ports:
      - 5506:3306
    depends_on:
      - edsphc-source
    volumes:
      - ./replica/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./setup_replication.sh:/setup_replication.sh
    networks:
      - overlay

networks:
  overlay:

