services:
  slave-database:
    image: mysql:8.0
    env_file:
      - ./replica.env
    container_name: "slave-database"
    restart: "on-failure"
    ports:
      - 4441:3306
    volumes:
      - ./mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
    networks:
      - replication-net

networks:
  replication-net:
