services:
  edsphc-source:
    image: mysql:8.0
    env_file:
      - ./edsphc-source.env
    container_name: "edsphc-source"
    restart: "on-failure"
    ports:
      - 3310:3306
    volumes:
      - ./mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - /mnt/edodida-backup:/var/lib/mysql
